export const CATEGORIES = ["All", "Electronics", "Clothing", "Home"];
export const BRANDS = ["Nike", "Adidas", "Sony"];

export const products = [
  {
    id: "running-shoes",
    title: "Running Shoes",
    price: 99,
    image: "https://m.media-amazon.com/images/I/71f3BmjCwtL.jpg",
    category: "Clothing",
    brand: "Nike",
    rating: 4.4,
    description: "Lightweight runners built for daily miles.",
  },
  {
    id: "wireless-headphones",
    title: "Wireless Headphones",
    price: 129,
    image: "https://m.media-amazon.com/images/I/610DB8Cwm7L.jpg",
    category: "Electronics",
    brand: "Sony",
    rating: 4.6,
    description: "Noise‑isolating over‑ears with long battery life.",
  },
  {
    id: "backpack",
    title: "Backpack",
    price: 129,
    image: "https://oliveplanet.in/cdn/shop/files/tactical_3_day_backpack_black_4a31c1a0-f75c-4636-9476-7c9c2f3e33bd_1280x.jpg?v=1695631833",
    category: "Home",
    brand: "Adidas",
    rating: 4.2,
    description: "Everyday 20L pack with padded sleeve.",
  },
  {
    id: "smartwatch",
    title: "Smartwatch",
    price: 249,
    image: "https://gourban.in/cdn/shop/files/SumoWebTools_1698039707-1698039711_236d9ae4-7378-40f5-8f9b-0b7447f8f3fd.webp?v=1705564100",
    category: "Electronics",
    brand: "Sony",
    rating: 4.1,
    description: "Track health, sleep, and notifications.",
  },
  {
    id: "sunglasses",
    title: "Sunglasses",
    price: 149,
    image: "https://www.dervin.in/cdn/shop/files/dervin-uv-protection-square-flat-lens-matte-frame-sunglasses-for-men-and-women-dervin-1.jpg?v=1720947730&width=1920",
    category: "Clothing",
    brand: "Adidas",
    rating: 4.0,
    description: "Polarized UV400 aviators.",
  },
  {
    id: "camera",
    title: "Digital Camera",
    price: 499,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRuGwTxlkNBRnbjL15bFlNCjfU1eUpdX-f3Vw&s",
    category: "Electronics",
    brand: "Sony",
    rating: 4.5,
    description: "Compact APS‑C with 4K video.",
  },
  {
    id: "tshirt",
    title: "T‑shirt",
    price: 29,
    image: "https://merchshop.in/wp-content/uploads/2021/07/Plain-black-Half-Sleeve-T-Shirt.png",
    category: "Clothing",
    brand: "Nike",
    rating: 3.9,
    description: "Soft cotton classic tee.",
  },
  {
    id: "smartphone",
    title: "Smartphone",
    price: 699,
    image: "https://images.samsung.com/is/image/samsung/p6pim/latin_en/sm-a566eliagto/gallery/latin-en-galaxy-a56-5g-sm-a566-sm-a566eliagto-thumb-545594778?$UX_EXT2_PNG$",
    category: "Electronics",
    brand: "Sony",
    rating: 4.8,
    description: "AMOLED 120Hz, 5G, 128GB.",
  },
];